/**
 * Render the social cards published beside individual pages.
 *
 * Reads the card content the changelog generator derived into `website/releases/cards.json`,
 * adds the standalone pages that carry their own card, and paints each one with Chromium at
 * 1200x630, the OpenGraph canvas. A changelog card's facts therefore come from the same derivation
 * as the page it belongs to, and this script only decides how they look. A standalone page's card
 * is its own copy, stated below: nothing derives it, so it holds only facts that outlive a
 * redraw — never a count that a redraw would silently leave stale.
 *
 * Rendering needs a browser, so it is a maintainer task rather than part of the website build:
 * `bun run generate:changelog` records which cards should exist and `--check` reports missing
 * images, while this script is what actually draws them.
 *
 * Usage, from the repository root:
 *   bun run website/scripts/generate-og.ts [slug]...
 *
 * With no arguments every card is redrawn. Point CHROMIUM at a browser binary to use one other
 * than Playwright's bundled build.
 */
import { mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const websiteDir = resolve(scriptsDir, "..");
const repoRoot = resolve(websiteDir, "..");
const cardsFile = join(websiteDir, "releases", "cards.json");
const changelogOutputDir = join(websiteDir, "public", "changelog", "og");
const fontFile = join(
  websiteDir,
  "node_modules",
  "@fontsource-variable",
  "jetbrains-mono",
  "files",
  "jetbrains-mono-latin-wght-normal.woff2",
);

/** Mirrors `SocialCard` in `scripts/generate-changelog.ts`. */
type SocialCard = {
  slug: string;
  title: string;
  tagline?: string;
  meta: string;
  chips?: string[];
  latest?: boolean;
  alt: string;
};

/** One card with the route it belongs to: its footer link and published file. */
type CardTarget = {
  card: SocialCard;
  /** Right-hand side of the footer; the page the card links to. */
  footer: string;
  /** Published path under `website/public`. */
  outputFile: string;
};

/**
 * Standalone pages that carry their own card rather than the site-wide image.
 *
 * Copy only — a card is regenerated by hand, so anything that changes between
 * redraws (how many extensions are listed, say) would go stale unnoticed.
 */
const PAGE_CARDS: CardTarget[] = [
  {
    card: {
      slug: "extensions",
      title: "Extensions",
      tagline:
        "Make hunk your own. Community extensions for panes, themes, highlighters, and more.",
      meta: "hunk extension install <owner>/<repo>",
      alt: "Hunk extensions: community extensions for panes, themes, highlighters, and more.",
    },
    footer: "hunk.dev/extensions",
    outputFile: join(websiteDir, "public", "extensions", "og.png"),
  },
];

const WIDTH = 1200;
const HEIGHT = 630;

/** Escape text interpolated into the card markup. */
function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/**
 * Paint one card.
 *
 * The palette and type are the site's own (`website/src/styles/brand.css`), so a card and the page
 * it links to read as one surface. Long titles step down a size rather than wrapping, because a
 * wrapped version number reads as a layout bug.
 */
function renderCardHtml({ card, footer }: CardTarget, fontDataUri: string) {
  const titleSize = card.title.length > 12 ? 82 : 104;
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  @font-face {
    font-family: "JetBrains Mono";
    src: url("${fontDataUri}") format("woff2-variations");
    font-weight: 100 800;
    font-display: block;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    width: ${WIDTH}px;
    height: ${HEIGHT}px;
    background: #f4f1ea;
    color: #16140f;
    font-family: "JetBrains Mono", monospace;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    padding: 64px;
  }
  .mark { font-size: 28px; font-weight: 700; letter-spacing: -0.02em; }
  .mid { display: flex; flex-direction: column; gap: 22px; }
  .vrow { display: flex; align-items: center; gap: 20px; }
  .title {
    font-size: ${titleSize}px;
    font-weight: 500;
    letter-spacing: -0.045em;
    line-height: 1;
    white-space: nowrap;
  }
  .pill {
    background: #bfe9c6;
    color: #0d3a18;
    font-size: 18px;
    font-weight: 500;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    padding: 7px 15px;
    border-radius: 999px;
  }
  .tagline { font-size: 31px; line-height: 1.4; color: #3a352b; max-width: 900px; }
  .chips { display: flex; gap: 10px; }
  .chip {
    border: 1px solid #dcd6c8;
    background: #fffdf8;
    color: #3a352b;
    font-size: 18px;
    padding: 6px 14px;
    border-radius: 6px;
  }
  .foot {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 20px;
    color: #6b6557;
    border-top: 1px solid #dcd6c8;
    padding-top: 24px;
  }
</style>
</head>
<body>
  <div class="mark">hunk</div>
  <div class="mid">
    <div class="vrow">
      <span class="title">${escapeHtml(card.title)}</span>
      ${card.latest ? '<span class="pill">Latest</span>' : ""}
    </div>
    ${card.tagline ? `<div class="tagline">${escapeHtml(card.tagline)}</div>` : ""}
    ${
      card.chips?.length
        ? `<div class="chips">${card.chips
            .map((chip) => `<span class="chip">${escapeHtml(chip)}</span>`)
            .join("")}</div>`
        : ""
    }
  </div>
  <div class="foot"><span>${escapeHtml(card.meta)}</span><span>${escapeHtml(footer)}</span></div>
</body>
</html>`;
}

const requested = new Set(process.argv.slice(2));
const changelogCards: CardTarget[] = (
  JSON.parse(readFileSync(cardsFile, "utf8")) as SocialCard[]
).map((card) => ({
  card,
  footer: "hunk.dev/changelog",
  outputFile: join(changelogOutputDir, `${card.slug}.png`),
}));
const targets = [...changelogCards, ...PAGE_CARDS];
const selected =
  requested.size > 0 ? targets.filter((target) => requested.has(target.card.slug)) : targets;

if (selected.length === 0) {
  const known = targets.map((target) => target.card.slug).join(", ");
  throw new Error(`No cards matched ${[...requested].join(", ")}. Known slugs: ${known}`);
}

const fontDataUri = `data:font/woff2;base64,${readFileSync(fontFile).toString("base64")}`;

// Draw into a scratch directory and move the results into place only once every card has
// rendered. Painting straight into the published directory meant a Chromium launch failure or a
// mid-run error left the committed image set partly deleted, with nothing to restore it from.
const stagingDir = mkdtempSync(join(tmpdir(), "hunk-og-"));

try {
  const browser = await chromium.launch(
    process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {},
  );
  try {
    const page = await browser.newPage({ viewport: { width: WIDTH, height: HEIGHT } });
    for (const target of selected) {
      const scratch = join(stagingDir, `${target.card.slug}.html`);
      writeFileSync(scratch, renderCardHtml(target, fontDataUri));
      await page.goto(`file://${scratch}`, { waitUntil: "networkidle" });
      await page.evaluate(() => document.fonts.ready);
      await page.screenshot({ path: join(stagingDir, `${target.card.slug}.png`) });
      rmSync(scratch);
      console.log(`${target.card.slug}.png`);
    }
  } finally {
    await browser.close();
  }

  // A stale image for a series that no longer exists would keep being served, so a full run owns
  // the changelog directory. A targeted run replaces only the cards it was asked for. Page cards
  // are named files rather than a generated set, so nothing sweeps them.
  if (requested.size === 0) {
    rmSync(changelogOutputDir, { recursive: true, force: true });
  }
  for (const target of selected) {
    mkdirSync(dirname(target.outputFile), { recursive: true });
    renameSync(join(stagingDir, `${target.card.slug}.png`), target.outputFile);
  }
} finally {
  rmSync(stagingDir, { recursive: true, force: true });
}

const written = selected.map((target) => target.outputFile.replace(`${repoRoot}/`, ""));
console.log(`Rendered ${selected.length} card(s):\n${written.join("\n")}`);
