import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Projects `CHANGELOG.md` into the release-notes pages published at hunk.dev/changelog.
 *
 * `CHANGELOG.md` stays the source of truth: this script parses it, groups releases by minor
 * series, merges the hand-authored overlay in `website/releases/notes.json`, and writes committed
 * Markdown into the Starlight docs collection. Nothing here may be hand-edited — regenerate with
 * `bun run generate:changelog` instead.
 *
 * Two invariants keep the output deterministic so `--check` can gate CI without network or Git:
 * release dates live in the committed `website/releases/dates.json`, and a date already recorded
 * there is never recomputed. Only a version with no recorded date consults Git tags, and a version
 * that has neither is rendered as unreleased.
 */

const REPO_ROOT = resolve(import.meta.dir, "..");
const REPO_URL = "https://github.com/modem-dev/hunk";
const SITE_ORIGIN = "https://hunk.dev";
const GENERATED_NOTICE =
  "<!-- GENERATED by `bun run generate:changelog`. Edit CHANGELOG.md or website/releases/notes.json instead. -->";

export const CHANGELOG_SOURCE = resolve(REPO_ROOT, "CHANGELOG.md");
export const RELEASE_NOTES_SOURCE = resolve(REPO_ROOT, "website", "releases", "notes.json");
export const RELEASE_DATES_SOURCE = resolve(REPO_ROOT, "website", "releases", "dates.json");
export const LATEST_RELEASE_PATH = resolve(REPO_ROOT, "website", "releases", "latest.json");
export const SOCIAL_CARDS_PATH = resolve(REPO_ROOT, "website", "releases", "cards.json");
export const SOCIAL_CARD_DIR = resolve(REPO_ROOT, "website", "public", "changelog", "og");
export const CHANGELOG_OUTPUT_DIR = resolve(
  REPO_ROOT,
  "website",
  "src",
  "content",
  "docs",
  "changelog",
);
export const CHANGELOG_FEED_PATH = resolve(REPO_ROOT, "website", "public", "changelog", "rss.xml");

/** One bullet from a release section, with its originating pull request when the entry names one. */
export type ChangeEntry = {
  description: string;
  pullRequest?: number;
};

/** One `### ...` block inside a release, such as `Minor Changes` or `Fixed`. */
export type ChangeSection = {
  title: string;
  entries: ChangeEntry[];
};

/** One `## <version>` block parsed out of `CHANGELOG.md`. */
export type ReleaseEntry = {
  version: string;
  prerelease: boolean;
  /** Date from a legacy `## [x.y.z] - YYYY-MM-DD` heading, when the entry carries one. */
  headingDate?: string;
  /** Raw Markdown of the hand-authored `### Highlights` block. */
  highlights?: string;
  sections: ChangeSection[];
};

/** Every release sharing a `major.minor` line, newest first. */
export type ReleaseSeries = {
  minor: string;
  releases: ReleaseEntry[];
};

/** Hand-authored additions for one minor series. Every field is optional. */
export type SeriesNotes = {
  summary?: string;
  /** Short phrase for the landing-page release ribbon, where a full sentence does not fit. */
  tagline?: string;
  video?: {
    mp4: string;
    webm?: string;
    poster?: string;
    /** ISO 8601 duration such as `PT1M24S`, used for the VideoObject description. */
    duration?: string;
    title?: string;
  };
  links?: { label: string; href: string }[];
};

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

/** Matches a release heading exactly, so trailing prose can never be mistaken for a version. */
const VERSION_PATTERN = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?$/;

/**
 * Split a version into comparable numeric parts, treating a prerelease as preceding its release.
 *
 * Prerelease identifiers compare pairwise, so `beta.2` precedes `beta.10` and `alpha` precedes
 * `beta`. Every component is a finite number: a comparator that returns `NaN` makes `sort`
 * behave arbitrarily, which previously let `0.19.0-rc` outrank `0.19.0`.
 */
function versionSortKey(version: string) {
  const [core = "", pre] = version.split("-", 2);
  const [major = "0", minor = "0", patch = "0"] = core.split(".");
  return {
    core: [major, minor, patch].map((part) => Number(part) || 0),
    // A release outranks all of its own prereleases, so absent prerelease metadata ranks highest.
    pre: pre === undefined ? undefined : pre.split("."),
  };
}

/** Compare two prerelease identifiers: numbers rank below strings, matching semver. */
function comparePrereleaseParts(a: string | undefined, b: string | undefined) {
  if (a === undefined || b === undefined) {
    // A shorter identifier list precedes a longer one with the same prefix (`beta` before `beta.1`).
    return a === undefined ? (b === undefined ? 0 : -1) : 1;
  }
  const aNumber = /^\d+$/.test(a) ? Number(a) : undefined;
  const bNumber = /^\d+$/.test(b) ? Number(b) : undefined;
  if (aNumber !== undefined && bNumber !== undefined) {
    return aNumber - bNumber;
  }
  if (aNumber !== undefined || bNumber !== undefined) {
    return aNumber === undefined ? 1 : -1;
  }
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Order two versions newest first. Always returns a finite number. */
export function compareVersionsDescending(a: string, b: string) {
  const left = versionSortKey(a);
  const right = versionSortKey(b);

  for (let index = 0; index < left.core.length; index += 1) {
    const difference = (right.core[index] ?? 0) - (left.core[index] ?? 0);
    if (difference !== 0) {
      return difference;
    }
  }

  if (left.pre === undefined || right.pre === undefined) {
    return left.pre === undefined ? (right.pre === undefined ? 0 : -1) : 1;
  }

  const length = Math.max(left.pre.length, right.pre.length);
  for (let index = 0; index < length; index += 1) {
    const difference = comparePrereleaseParts(right.pre[index], left.pre[index]);
    if (difference !== 0) {
      return difference;
    }
  }
  return 0;
}

/** Return the `major.minor` series a version belongs to. */
export function minorSeriesOf(version: string) {
  const [major = "0", minor = "0"] = version.split("-", 1)[0]?.split(".") ?? [];
  return `${major}.${minor}`;
}

/**
 * Strip Changesets' link preamble from one bullet and recover its pull request number.
 *
 * Entries arrive in three shapes across the file's history: `[#711](url) [`sha`](url) - text`,
 * `[`sha`](url) - text` when the change landed without a linked pull request, and the legacy
 * `sha: text`. Anything else is kept verbatim.
 */
export function parseChangeEntry(raw: string): ChangeEntry {
  const text = raw.trim();
  const pullRequestMatch = text.match(/^\[#(\d+)\]\([^)]+\)\s*/);
  let rest = text;
  let pullRequest: number | undefined;
  if (pullRequestMatch?.[1]) {
    pullRequest = Number(pullRequestMatch[1]);
    rest = rest.slice(pullRequestMatch[0].length);
  }

  // Drop any commit links that follow the pull-request link; the description carries the meaning.
  rest = rest.replace(/^(?:\[`[0-9a-f]+`\]\([^)]+\)\s*)+/, "");
  rest = rest.replace(/^-\s+/, "");
  // Legacy entries prefixed a bare short SHA instead of linking it.
  rest = rest.replace(/^[0-9a-f]{7,40}:\s+/, "");

  return pullRequest === undefined
    ? { description: rest.trim() }
    : { description: rest.trim(), pullRequest };
}

/**
 * Split Markdown into top-level blocks at headings of one depth, ignoring fenced code.
 *
 * A changeset description may contain a fenced block whose lines start with `#` or `-`. Splitting
 * on a bare regex would treat those as structure and silently discard everything after them, so
 * fences are tracked and their contents are never treated as headings.
 */
function splitOnHeadings(markdown: string, marker: string) {
  const blocks: string[][] = [];
  let fence: string | undefined;

  for (const line of markdown.split("\n")) {
    const fenceMatch = line.match(/^\s*(```+|~~~+)/);
    if (fenceMatch?.[1]) {
      // A fence closes only on its own delimiter, so ``` inside a ~~~ block stays content.
      if (fence === undefined) {
        fence = fenceMatch[1][0];
      } else if (fenceMatch[1].startsWith(fence)) {
        fence = undefined;
      }
    }

    if (fence === undefined && line.startsWith(marker)) {
      blocks.push([line.slice(marker.length)]);
      continue;
    }
    blocks.at(-1)?.push(line);
  }

  return blocks.map((lines) => lines.join("\n"));
}

/**
 * Report whether a line is a Markdown link-reference definition such as `[0.9.1]: https://…`.
 *
 * `CHANGELOG.md` closes with a block of these linking every legacy version heading to its compare
 * view. They are document metadata belonging to no release, and folding them into prose would
 * publish the whole table as the text of the oldest release's last entry.
 */
function isLinkReferenceDefinition(line: string) {
  return /^\[[^\]]+\]:\s+\S+/.test(line.trim());
}

/**
 * Collect the `- ` bullets in one section body.
 *
 * Wrapped continuation lines fold into the bullet above them, but an indented sub-bullet keeps its
 * own line so a nested list renders as a list rather than as run-on prose with stray dashes.
 */
function parseEntries(body: string): ChangeEntry[] {
  const entries: string[] = [];
  let fence: string | undefined;

  for (const line of body.split("\n")) {
    const fenceMatch = line.match(/^\s*(```+|~~~+)/);
    if (fenceMatch?.[1]) {
      if (fence === undefined) {
        fence = fenceMatch[1][0];
      } else if (fenceMatch[1].startsWith(fence)) {
        fence = undefined;
      }
    }

    if (fence === undefined && line.startsWith("- ")) {
      entries.push(line.slice(2));
      continue;
    }
    // Reference definitions are document metadata, not prose, but only outside a fence where an
    // example of one would be content.
    if (fence === undefined && isLinkReferenceDefinition(line)) {
      continue;
    }
    if (entries.length === 0) {
      continue;
    }
    // Inside a fence, blank lines and indentation are content and must survive verbatim.
    if (fence !== undefined || /^\s+[-*] /.test(line)) {
      entries[entries.length - 1] += `\n${line}`;
      continue;
    }
    if (line.trim() !== "") {
      entries[entries.length - 1] += ` ${line.trim()}`;
    }
  }

  return entries.map(parseChangeEntry).filter((entry) => entry.description !== "");
}

/**
 * Parse `CHANGELOG.md` into releases, newest first.
 *
 * Handles both formats the file carries: the Changesets output used since 0.16.0 and the
 * Keep a Changelog headings (`## [0.15.3] - 2026-06-13`) used before it.
 */
export function parseChangelog(markdown: string): ReleaseEntry[] {
  const releases: ReleaseEntry[] = [];

  for (const block of splitOnHeadings(markdown, "## ")) {
    const newline = block.indexOf("\n");
    const heading = (newline === -1 ? block : block.slice(0, newline)).trim();
    const body = newline === -1 ? "" : block.slice(newline + 1);

    const legacy = heading.match(/^\[([^\]]+)\]\s*-\s*(\d{4}-\d{2}-\d{2})$/);
    const version = legacy?.[1] ?? heading;
    // Matched in full: a heading like `## 1.2.3 (hotfix)` must not become a version whose text
    // then flows into anchors, install commands, and page URLs.
    if (!VERSION_PATTERN.test(version)) {
      continue;
    }

    const sections: ChangeSection[] = [];
    let highlights: string | undefined;
    for (const sectionBlock of splitOnHeadings(body, "### ")) {
      const sectionNewline = sectionBlock.indexOf("\n");
      const title = (
        sectionNewline === -1 ? sectionBlock : sectionBlock.slice(0, sectionNewline)
      ).trim();
      const sectionBody = sectionNewline === -1 ? "" : sectionBlock.slice(sectionNewline + 1);

      if (title === "Highlights") {
        // Taken raw rather than parsed into entries, so the reference block is filtered here too.
        highlights = sectionBody
          .split("\n")
          .filter((line) => !isLinkReferenceDefinition(line))
          .join("\n")
          .trim();
        continue;
      }

      const entries = parseEntries(sectionBody);
      // Legacy releases left empty `### Changed` headings behind; drop them rather than render them.
      if (entries.length > 0) {
        sections.push({ title, entries });
      }
    }

    releases.push({
      version,
      prerelease: version.includes("-"),
      ...(legacy?.[2] ? { headingDate: legacy[2] } : {}),
      ...(highlights ? { highlights } : {}),
      sections,
    });
  }

  return releases.sort((a, b) => compareVersionsDescending(a.version, b.version));
}

/** Group parsed releases into minor series, newest series first. */
export function groupIntoSeries(releases: readonly ReleaseEntry[]): ReleaseSeries[] {
  const byMinor = new Map<string, ReleaseEntry[]>();
  for (const release of releases) {
    const minor = minorSeriesOf(release.version);
    const bucket = byMinor.get(minor);
    if (bucket) {
      bucket.push(release);
    } else {
      byMinor.set(minor, [release]);
    }
  }

  return [...byMinor.entries()]
    .map(([minor, entries]) => ({
      minor,
      releases: entries.sort((a, b) => compareVersionsDescending(a.version, b.version)),
    }))
    .sort((a, b) => compareVersionsDescending(`${a.minor}.0`, `${b.minor}.0`));
}

/**
 * Read one committed JSON input, treating only a missing file as empty.
 *
 * Malformed JSON fails loudly instead: silently reading a corrupted `dates.json` as `{}` would
 * mark every release unreleased, dropping the whole feed and every install command with no
 * diagnostic and a clean exit code.
 */
function readJsonInput<T>(path: string): T | Record<string, never> {
  let text: string;
  try {
    text = readFileSync(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return {};
    }
    throw error;
  }
  try {
    return JSON.parse(text) as T;
  } catch (error) {
    throw new Error(`${path} is not valid JSON: ${(error as Error).message}`);
  }
}

/** Choose an annotated tag's publication date, falling back to its commit for lightweight tags. */
export function resolveTagDate(taggerDate: string, commitDate: string) {
  const validDate = (value: string) =>
    /^\d{4}-\d{2}-\d{2}$/.test(value.trim()) ? value.trim() : undefined;
  return validDate(taggerDate) ?? validDate(commitDate);
}

/**
 * Resolve the tag date for one version, or `undefined` when Git cannot answer.
 *
 * Shallow clones and tagless checkouts are expected — the committed date map is what makes
 * generation deterministic, and this only ever fills gaps in it. Annotated tags use their tagger
 * date because that records publication; lightweight tags fall back to the tagged commit date.
 */
function tagDate(version: string): string | undefined {
  try {
    const taggerDate = execFileSync(
      "git",
      ["for-each-ref", "--format=%(taggerdate:short)", `refs/tags/v${version}`],
      {
        cwd: REPO_ROOT,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      },
    );
    const commitDate = execFileSync("git", ["log", "-1", "--format=%as", `v${version}`], {
      cwd: REPO_ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return resolveTagDate(taggerDate, commitDate);
  } catch {
    return undefined;
  }
}

/**
 * Fill in dates for versions the committed map has not recorded yet.
 *
 * Recorded dates are never recomputed, so regeneration is stable even as tags move between
 * checkouts. Returns the merged map so callers can persist it.
 */
export function resolveDates(
  releases: readonly ReleaseEntry[],
  recorded: Record<string, string>,
  lookup: (version: string) => string | undefined = tagDate,
): Record<string, string> {
  const resolved: Record<string, string> = {};
  for (const release of releases) {
    // Carry a recorded date forward untouched; only a version without one consults the lookup.
    const date = recorded[release.version] ?? release.headingDate ?? lookup(release.version);
    if (date) {
      resolved[release.version] = date;
    }
  }
  // Build from the release list rather than merging onto it, so a version that leaves CHANGELOG.md
  // does not linger in the committed map.
  return Object.fromEntries(
    Object.entries(resolved).sort(([a], [b]) => compareVersionsDescending(a, b)),
  );
}

/**
 * One social card's content, in the order it is rendered.
 *
 * The renderer in `website/scripts/generate-og.ts` reads only this, so the facts on a card come
 * from the same derivation as the page it belongs to rather than being re-read from Markdown.
 */
export type SocialCard = {
  /** Published path the card belongs to, used to name the image file. */
  slug: string;
  title: string;
  /** Editorial summary only; absent when a series has none, and the card then omits the line. */
  tagline?: string;
  meta: string;
  /** Patch versions in the series, newest first. Absent for a single-release series. */
  chips?: string[];
  latest?: boolean;
  /** Alt text published beside the image. */
  alt: string;
};

/** Path of the rendered card for one social-card slug. */
export function socialCardPath(slug: string) {
  return `/changelog/og/${slug}.png`;
}

/** Build the stable in-page anchor for one version, e.g. `0.18.2` becomes `v0-18-2`. */
export function versionAnchor(version: string) {
  return `v${version.replaceAll(".", "-")}`;
}

/**
 * Report whether a release is published by checking for its recorded tag date.
 *
 * A version-preparation branch describes a release before its tag and npm publication exist, so
 * position in `CHANGELOG.md` is not publication evidence. This includes dated prereleases, whose
 * notes belong on the website even though they never become the default install target.
 */
export function isPublished(release: ReleaseEntry, dates: Record<string, string>) {
  return dates[release.version] !== undefined;
}

/** Report whether a published release is stable enough to advertise as the default install. */
export function isStablePublished(release: ReleaseEntry, dates: Record<string, string>) {
  return !release.prerelease && isPublished(release, dates);
}

/** List a series' published releases, including prereleases, newest first. */
function publishedReleases(series: ReleaseSeries, dates: Record<string, string>) {
  return series.releases.filter((release) => isPublished(release, dates));
}

/** List a series' published stable releases, newest first. */
function stablePublishedReleases(series: ReleaseSeries, dates: Record<string, string>) {
  return series.releases.filter((release) => isStablePublished(release, dates));
}

/** Report whether a published series has only reached prerelease versions. */
function isPrereleaseOnlySeries(series: ReleaseSeries, dates: Record<string, string>) {
  return (
    publishedReleases(series, dates).length > 0 &&
    stablePublishedReleases(series, dates).length === 0
  );
}

/** Render `2026-08-16` as `August 16, 2026`. */
export function formatDate(iso: string) {
  const [year, month, day] = iso.split("-");
  const name = MONTHS[Number(month) - 1];
  return name && year && day ? `${name} ${Number(day)}, ${year}` : iso;
}

/**
 * Quote a value as a YAML frontmatter scalar.
 *
 * Prefers single quotes when the value contains double quotes but no single quotes, matching what
 * the repository formatter would rewrite the line to. Generated output has to survive
 * `bun run format` unchanged, or `--check` reports every page as stale.
 */
export function yamlString(value: string) {
  if (value.includes('"') && !value.includes("'")) {
    return `'${value}'`;
  }
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Reduce Markdown prose to plain text for frontmatter descriptions and feed summaries.
 *
 * Only the inline constructs the changelog actually uses are unwrapped; the result is a single
 * line so it can be embedded in YAML and XML without further escaping.
 */
export function toPlainText(markdown: string) {
  return markdown
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replaceAll("**", "")
    .replaceAll("`", "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Truncate plain text on a word boundary so descriptions stay within search-result length. */
export function truncate(text: string, limit: number) {
  if (text.length <= limit) {
    return text;
  }
  const clipped = text.slice(0, limit);
  const lastSpace = clipped.lastIndexOf(" ");
  // Always break on a word boundary when the clip contains one; a mid-word cut reads as corruption
  // in a search result or feed summary.
  const body = lastSpace > 0 ? clipped.slice(0, lastSpace) : clipped;
  return `${body.replace(/[,;:.\s]+$/, "")}…`;
}

/**
 * Split a `### Highlights` block into its lead paragraph and the bullets beneath it.
 *
 * The lead paragraph becomes the page's opening summary, so the rendered Highlights section keeps
 * only the bullets and no sentence appears twice on the page.
 */
export function splitHighlights(highlights: string) {
  const paragraphs = highlights.split("\n\n");
  const lead = paragraphs[0]?.trimStart().startsWith("-") ? undefined : paragraphs[0]?.trim();
  const body = (lead === undefined ? paragraphs : paragraphs.slice(1)).join("\n\n").trim();
  return { ...(lead ? { lead } : {}), ...(body ? { body } : {}) };
}

/**
 * Choose the editorial summary for a series.
 *
 * Prefers the hand-authored overlay, then the lead paragraph of the newest `### Highlights` block.
 * Returns `undefined` when neither exists so callers can fall back to a factual description rather
 * than promoting an arbitrary bullet into the page description.
 */
export function seriesSummary(series: ReleaseSeries, notes: SeriesNotes | undefined) {
  if (notes?.summary) {
    return notes.summary;
  }
  for (const release of series.releases) {
    const lead = release.highlights ? splitHighlights(release.highlights).lead : undefined;
    if (lead) {
      return toPlainText(lead);
    }
  }
  return undefined;
}

/** Describe a series' published span as a single phrase, or `undefined` when no release is dated. */
function seriesSpan(series: ReleaseSeries, dates: Record<string, string>) {
  const published = publishedReleases(series, dates).map(
    (release) => dates[release.version] as string,
  );
  const newest = published[0];
  const oldest = published.at(-1);
  if (!newest || !oldest) {
    return undefined;
  }
  return oldest === newest ? formatDate(newest) : `${formatDate(oldest)} – ${formatDate(newest)}`;
}

/** Build a factual description for a series with no hand-authored or changelog-authored summary. */
function factualSummary(series: ReleaseSeries, dates: Record<string, string>) {
  const count = series.releases.length;
  const span = seriesSpan(series, dates);
  const releases = `${count} release${count === 1 ? "" : "s"}`;
  return span
    ? `Release notes for Hunk ${series.minor}: ${releases}, ${span}.`
    : `Release notes for Hunk ${series.minor}: ${releases}.`;
}

/** Resolve the summary a series page and index entry share. */
export function resolveSummary(
  series: ReleaseSeries,
  notes: SeriesNotes | undefined,
  dates: Record<string, string>,
) {
  return seriesSummary(series, notes) ?? factualSummary(series, dates);
}

/**
 * Render the frontmatter `head` entries that point one page at its own social card.
 *
 * The global `head` in `astro.config.mjs` sets a site-wide image; Starlight merges page entries
 * over it by tag and property, so these replace rather than duplicate it.
 */
function renderCardHead(card: SocialCard) {
  const url = `${SITE_ORIGIN}${socialCardPath(card.slug)}`;
  const tags: [string, string][] = [
    ["og:image", url],
    ["og:image:alt", card.alt],
  ];
  return [
    "head:",
    ...tags.flatMap(([property, content]) => [
      "  - tag: meta",
      "    attrs:",
      `      property: ${property}`,
      `      content: ${yamlString(content)}`,
    ]),
    // Twitter reads its own name-based tags rather than the property-based OpenGraph ones.
    "  - tag: meta",
    "    attrs:",
    "      name: twitter:image",
    `      content: ${yamlString(url)}`,
  ];
}

/** Render one bullet, appending its pull-request link when the entry carries one. */
function renderEntry(entry: ChangeEntry) {
  const suffix =
    entry.pullRequest === undefined
      ? ""
      : ` ([#${entry.pullRequest}](${REPO_URL}/pull/${entry.pullRequest}))`;
  return `- ${entry.description}${suffix}`;
}

/** Escape a value for an HTML double-quoted attribute. */
function attribute(value: string) {
  return value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;");
}

/**
 * Serialize a value for embedding inside a `<script>` element.
 *
 * `JSON.stringify` leaves `</script>` intact, which would close the element early and turn the
 * remainder of the payload into markup.
 */
function jsonForScript(value: unknown) {
  return JSON.stringify(value).replaceAll("<", "\\u003c").replaceAll("\u2028", "\\u2028");
}

/** Render the self-hosted release video, including the schema search engines index it by. */
function renderVideo(video: NonNullable<SeriesNotes["video"]>, minor: string, summary: string) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: video.title ?? `What's new in Hunk ${minor}`,
    description: summary,
    contentUrl: video.mp4,
    ...(video.poster ? { thumbnailUrl: `${SITE_ORIGIN}${video.poster}` } : {}),
    ...(video.duration ? { duration: video.duration } : {}),
  };

  const sources = [
    video.webm ? `    <source src="${attribute(video.webm)}" type="video/webm" />` : undefined,
    `    <source src="${attribute(video.mp4)}" type="video/mp4" />`,
  ].filter(Boolean);

  return [
    `<video class="changelog-video" controls preload="none"${video.poster ? ` poster="${attribute(video.poster)}"` : ""}>`,
    ...sources,
    "  </video>",
    "",
    `<script type="application/ld+json" is:inline>${jsonForScript(schema)}</script>`,
  ].join("\n");
}

/** Render one minor-series page. */
export function renderSeriesPage({
  series,
  notes,
  dates,
  card,
  newer,
  older,
  latestReleasedVersion,
}: {
  series: ReleaseSeries;
  notes: SeriesNotes | undefined;
  dates: Record<string, string>;
  card?: SocialCard;
  newer?: string;
  older?: string;
  latestReleasedVersion?: string;
}) {
  // The page body carries a summary only when one was actually written. The factual fallback still
  // fills the frontmatter description, which search results need, but as a paragraph it would just
  // restate the dateline directly above it.
  const editorialSummary = seriesSummary(series, notes);
  const summary = resolveSummary(series, notes, dates);
  const newestHighlights = series.releases.find((release) => release.highlights)?.highlights;
  const highlightBullets = newestHighlights ? splitHighlights(newestHighlights).body : undefined;
  // Only offer an install command for a version that is actually published; the page can be
  // generated from a release-preparation branch before its tag and npm publication exist.
  const installable = stablePublishedReleases(series, dates)[0]?.version;
  const isCurrent = latestReleasedVersion !== undefined && installable === latestReleasedVersion;

  const releaseCount = series.releases.length;
  const prereleaseOnly = isPrereleaseOnlySeries(series, dates);
  const dateline = [
    prereleaseOnly ? "Prerelease" : undefined,
    seriesSpan(series, dates) ?? "Unreleased",
    `${releaseCount} release${releaseCount === 1 ? "" : "s"}`,
  ]
    .filter(Boolean)
    .join(" · ");

  const lines: string[] = [
    "---",
    `title: Hunk ${series.minor}`,
    `description: ${yamlString(truncate(toPlainText(summary), 155))}`,
    // Astro slugifies the filename and would drop the dot, publishing `0.18` as `/changelog/018/`.
    `slug: changelog/${series.minor}`,
    // The page is generated; an edit link would invite hand-edits that regeneration overwrites.
    "editUrl: false",
    ...(card ? renderCardHead(card) : []),
    "---",
    "",
    GENERATED_NOTICE,
    "",
    dateline,
    "",
    ...(editorialSummary ? [editorialSummary, ""] : []),
  ];

  if (notes?.video) {
    lines.push(renderVideo(notes.video, series.minor, toPlainText(summary)), "");
  }

  if (installable) {
    if (isCurrent) {
      lines.push(
        "New to Hunk? Use the default installer. It verifies downloads when release checksums and local tooling are available, and warns otherwise:",
        "",
        "```sh",
        "curl -fsSL https://hunk.dev/install.sh | sh",
        "```",
        "",
        "Already on Hunk 0.20 or newer with the default install script, npm, or Homebrew? Move to this release with Hunk's canonical update command:",
        "",
        "```sh",
        "hunk update",
        "```",
        "",
        "On an older Hunk release, update once through the installer or package manager that installed it, then use `hunk update`. mise, Nix, source, and custom-directory installs remain owned by their own update workflows. This is the current release; see [all install options](/docs/start/install/).",
        "",
      );
    } else {
      // A superseded release needs an explicitly pinned installer. The default installer and
      // Homebrew both track latest, so offering either here would silently install another series.
      lines.push(
        "```sh",
        `npm i -g hunkdiff@${installable}`,
        "```",
        "",
        `Hunk ${series.minor} is no longer the current release. See [the latest release](/changelog/) or [all install options](/docs/start/install/).`,
        "",
      );
    }
  }

  if (highlightBullets) {
    lines.push("## Highlights", "", highlightBullets, "");
  }

  if (notes?.links?.length) {
    lines.push(
      "## Related documentation",
      "",
      ...notes.links.map((link) => `- [${link.label}](${link.href})`),
      "",
    );
  }

  lines.push("## Releases in this series", "");

  for (const release of series.releases) {
    const date = dates[release.version];
    const meta = date ? formatDate(date) : "Unreleased";

    // Astro derives `#0182` from the heading text. Emit a stable, readable anchor beside it so a
    // single patch release can be linked from an issue, a release body, or the update notice.
    // It doubles as the rule between releases: Starlight renders headings inline inside a wrapper,
    // so a border on the heading itself would only span its text.
    lines.push(
      `<a class="release-separator" id="${versionAnchor(release.version)}"></a>`,
      "",
      `### ${release.version}`,
      "",
      meta,
      "",
    );

    if (release.sections.length === 0) {
      lines.push("No user-facing changes.", "");
      continue;
    }

    for (const section of release.sections) {
      lines.push(`#### ${section.title}`, "", ...section.entries.map(renderEntry), "");
    }
  }

  const around = [
    newer ? `[Newer: Hunk ${newer}](/changelog/${newer}/)` : undefined,
    older ? `[Older: Hunk ${older}](/changelog/${older}/)` : undefined,
    "[All releases](/changelog/)",
  ].filter(Boolean);
  lines.push("---", "", around.join(" · "), "");

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

/** Render the `/changelog/` index covering every series. */
export function renderIndexPage({
  seriesList,
  notes,
  dates,
  card,
}: {
  seriesList: readonly ReleaseSeries[];
  notes: Record<string, SeriesNotes>;
  dates: Record<string, string>;
  card?: SocialCard;
}) {
  const lines: string[] = [
    "---",
    "title: Changelog",
    "editUrl: false",
    "description: " +
      yamlString(
        "Every Hunk release, newest first — features, fixes, and performance work in the terminal diff viewer.",
      ),
    "tableOfContents: false",
    ...(card ? renderCardHead(card) : []),
    "---",
    "",
    GENERATED_NOTICE,
    "",
    // The page structure explains itself; only the two off-page destinations need stating.
    `[RSS](${SITE_ORIGIN}/changelog/rss.xml) · [CHANGELOG.md](${REPO_URL}/blob/main/CHANGELOG.md)`,
    "",
  ];

  // "Latest" tracks the newest *published* series, not the newest heading in CHANGELOG.md: a
  // release-preparation branch adds its section before the tag exists, and that series is
  // unreleased until the tag date lands.
  const latestPublished = seriesList.find(
    (series) => stablePublishedReleases(series, dates).length > 0,
  )?.minor;

  seriesList.forEach((series) => {
    // Only an editorial summary earns a paragraph here; the factual fallback would just restate
    // the release count and date span already shown on the meta line below.
    const summary = seriesSummary(series, notes[series.minor]);
    const versions = series.releases;
    const published = seriesSpan(series, dates) !== undefined;
    const prereleaseOnly = isPrereleaseOnlySeries(series, dates);

    const span = seriesSpan(series, dates);
    const changeCount = series.releases.reduce(
      (total, release) =>
        total + release.sections.reduce((count, section) => count + section.entries.length, 0),
      0,
    );
    const meta = [
      series.minor === latestPublished ? "Latest" : undefined,
      prereleaseOnly ? "Prerelease" : published ? undefined : "Unreleased",
      span,
      `${versions.length} release${versions.length === 1 ? "" : "s"}`,
      `${changeCount} change${changeCount === 1 ? "" : "s"}`,
    ]
      .filter(Boolean)
      .join(" · ");

    lines.push(
      `## [Hunk ${series.minor}](/changelog/${series.minor}/)`,
      "",
      meta,
      "",
      ...(summary ? [truncate(toPlainText(summary), 240), ""] : []),
    );
  });

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

/** Columns the repository formatter wraps at; generated JSON has to agree or `--check` fails. */
const PRINT_WIDTH = 100;

/**
 * Serialize JSON the way the repository formatter would print it.
 *
 * `JSON.stringify` always expands arrays, while oxfmt keeps an array of primitives on one line
 * while it fits inside the print width. Emitting the formatter's own shape keeps generated files
 * stable across `bun run format`, the same reason `generate-docs.ts` pre-formats its tables.
 */
export function formatJson(
  value: unknown,
  indent = 0,
  /** Column the value starts at, which is past its key when it is an object property. */
  column = indent,
  /** Whether a comma follows this value, which counts toward the line's width. */
  trailingComma = false,
): string {
  const pad = " ".repeat(indent);
  const inner = " ".repeat(indent + 2);

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }
    const last = value.length - 1;
    const parts = value.map((item, index) =>
      formatJson(item, indent + 2, indent + 2, index < last),
    );
    // Only primitives collapse; an array holding objects always breaks, as the formatter does.
    if (value.every((item) => item === null || typeof item !== "object")) {
      const inline = `[${parts.join(", ")}]`;
      // Measure the whole printed line: the key already consumed columns before this value, and a
      // comma may follow it. Ignoring the key inlined a 104-column `"chips": [...]` that the
      // formatter then rewrapped, which is exactly the drift this function exists to avoid.
      if (column + inline.length + (trailingComma ? 1 : 0) <= PRINT_WIDTH) {
        return inline;
      }
    }
    return `[\n${parts.map((part) => `${inner}${part}`).join(",\n")}\n${pad}]`;
  }

  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    if (entries.length === 0) {
      return "{}";
    }
    const lastEntry = entries.length - 1;
    const body = entries
      .map(([key, item], index) => {
        const label = `${JSON.stringify(key)}: `;
        const printed = formatJson(item, indent + 2, indent + 2 + label.length, index < lastEntry);
        return `${inner}${label}${printed}`;
      })
      .join(",\n");
    return `{\n${body}\n${pad}}`;
  }

  return JSON.stringify(value);
}

/** Escape text for inclusion in an XML text node or attribute. */
function xmlEscape(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/**
 * Render the RSS feed.
 *
 * Stable releases keep one item per minor series, version-anchored when that exact version had a
 * beta so promotion reaches subscribers with a new GUID. Each prerelease also gets an anchored item
 * of its own.
 */
export function renderFeed({
  seriesList,
  notes,
  dates,
}: {
  seriesList: readonly ReleaseSeries[];
  notes: Record<string, SeriesNotes>;
  dates: Record<string, string>;
}) {
  const entries = seriesList.flatMap((series) => {
    const summary = truncate(toPlainText(resolveSummary(series, notes[series.minor], dates)), 400);
    const seriesLink = `${SITE_ORIGIN}/changelog/${series.minor}/`;
    const stable = stablePublishedReleases(series, dates)[0];
    const prereleases = publishedReleases(series, dates).filter((release) => release.prerelease);
    // A stable promotion needs a versioned GUID when its own beta was already announced. An older
    // beta in the same series must not re-announce an unrelated current patch.
    const promotesPrerelease =
      stable && prereleases.some((release) => release.version.startsWith(`${stable.version}-`));
    const stableLink = promotesPrerelease
      ? `${seriesLink}#${versionAnchor(stable.version)}`
      : seriesLink;
    const stableEntry = stable
      ? [
          {
            version: stable.version,
            title: `Hunk ${series.minor}`,
            link: stableLink,
            date: dates[stable.version],
            summary,
          },
        ]
      : [];
    const prereleaseEntries = prereleases.map((release) => ({
      version: release.version,
      title: `Hunk ${release.version} (Prerelease)`,
      link: `${seriesLink}#${versionAnchor(release.version)}`,
      date: dates[release.version],
      summary,
    }));
    return [...stableEntry, ...prereleaseEntries];
  });
  entries.sort((a, b) =>
    a.date === b.date
      ? compareVersionsDescending(a.version, b.version)
      : (b.date ?? "").localeCompare(a.date ?? ""),
  );
  const items = entries.map(({ title, link, date, summary }) =>
    [
      "    <item>",
      `      <title>${xmlEscape(title)}</title>`,
      `      <link>${link}</link>`,
      `      <guid isPermaLink="true">${link}</guid>`,
      `      <pubDate>${new Date(`${date}T00:00:00Z`).toUTCString()}</pubDate>`,
      `      <description>${xmlEscape(summary)}</description>`,
      "    </item>",
    ].join("\n"),
  );

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">',
    "  <channel>",
    "    <title>Hunk releases</title>",
    `    <link>${SITE_ORIGIN}/changelog/</link>`,
    "    <description>Release notes for Hunk, the review-first terminal diff viewer.</description>",
    "    <language>en</language>",
    `    <atom:link href="${SITE_ORIGIN}/changelog/rss.xml" rel="self" type="application/rss+xml" />`,
    ...items,
    "  </channel>",
    "</rss>",
    "",
  ].join("\n");
}

/** Describe a series' size as `N releases · N changes`. */
function seriesCounts(series: ReleaseSeries) {
  const releases = series.releases.length;
  const changes = series.releases.reduce(
    (total, release) =>
      total + release.sections.reduce((n, section) => n + section.entries.length, 0),
    0,
  );
  return `${releases} release${releases === 1 ? "" : "s"} · ${changes} change${changes === 1 ? "" : "s"}`;
}

/** Build the social card for one minor series. */
export function buildSeriesCard({
  series,
  notes,
  dates,
  latest,
}: {
  series: ReleaseSeries;
  notes: SeriesNotes | undefined;
  dates: Record<string, string>;
  latest: boolean;
}): SocialCard {
  const tagline = seriesSummary(series, notes);
  const published = publishedReleases(series, dates);
  const meta = [
    isPrereleaseOnlySeries(series, dates) ? "Prerelease" : undefined,
    seriesSpan(series, dates) ?? "Unreleased",
    seriesCounts(series),
  ]
    .filter(Boolean)
    .join(" · ");

  return {
    slug: series.minor,
    title: `Hunk ${series.minor}`,
    // A card with no editorial summary drops the line rather than padding it with the factual
    // fallback; roughly half the series have never had one written.
    // Three lines at the card's type size; longer taglines are cut rather than shrinking the card.
    ...(tagline ? { tagline: truncate(toPlainText(tagline), 140) } : {}),
    meta,
    // Chips make the one-page-per-series idea legible, so they only appear when there is more
    // than one release to show.
    ...(published.length > 1 ? { chips: published.map((release) => release.version) } : {}),
    ...(latest ? { latest: true } : {}),
    alt: `Hunk ${series.minor} release notes — ${meta}`,
  };
}

/** Build the social card for the changelog index. */
export function buildIndexCard(
  seriesList: readonly ReleaseSeries[],
  dates: Record<string, string>,
): SocialCard {
  const published = seriesList.filter((series) => publishedReleases(series, dates).length > 0);
  const allDates = published
    .flatMap((series) => publishedReleases(series, dates).map((r) => dates[r.version] as string))
    .sort();
  const first = allDates[0];
  const last = allDates.at(-1);
  const span = first && last ? `${monthAndYear(first)} – ${monthAndYear(last)}` : undefined;
  const meta = [`${published.length} release series`, span].filter(Boolean).join(" · ");

  // The ellipsis stands for series the card had no room for, so it only appears when some were
  // actually left off. Appending it unconditionally claimed more history than the card was showing.
  const shown = published.slice(0, 5).map((series) => series.minor);
  const chips = published.length > shown.length ? [...shown, "…"] : shown;

  return {
    slug: "index",
    title: "Changelog",
    tagline: "Every Hunk release, grouped by minor series.",
    meta,
    ...(chips.length > 0 ? { chips } : {}),
    alt: `Hunk changelog — ${meta}`,
  };
}

/** Render `2026-08-16` as `August 2026`, for spans that cover whole months. */
function monthAndYear(iso: string) {
  const [year, month] = iso.split("-");
  const name = MONTHS[Number(month) - 1];
  return name && year ? `${name} ${year}` : iso;
}

/** Produce every committed changelog artifact, keyed by absolute path. */
export function generateChangelogArtifacts({
  markdown = readFileSync(CHANGELOG_SOURCE, "utf8"),
  notes = readJsonInput<Record<string, SeriesNotes>>(RELEASE_NOTES_SOURCE),
  recordedDates = readJsonInput<Record<string, string>>(RELEASE_DATES_SOURCE),
  lookupDate = tagDate,
}: {
  markdown?: string;
  notes?: Record<string, SeriesNotes>;
  recordedDates?: Record<string, string>;
  lookupDate?: (version: string) => string | undefined;
} = {}) {
  const parsedReleases = parseChangelog(markdown);
  const dates = resolveDates(parsedReleases, recordedDates, lookupDate);
  // Stable preparation branches keep their existing Unreleased page, while prerelease pages appear
  // only after the tag date proves that users can actually install that beta.
  const releases = parsedReleases.filter(
    (release) => !release.prerelease || isPublished(release, dates),
  );
  const seriesList = groupIntoSeries(releases);
  const latestReleasedVersion = releases.find((release) =>
    isStablePublished(release, dates),
  )?.version;

  // The landing page reads this rather than the pages themselves, so its release ribbon stays a
  // static import instead of a build-time parse of generated Markdown.
  const latestSeries = latestReleasedVersion
    ? seriesList.find((series) => series.minor === minorSeriesOf(latestReleasedVersion))
    : undefined;
  const latest = latestSeries
    ? {
        version: latestReleasedVersion,
        minor: latestSeries.minor,
        date: dates[latestReleasedVersion as string],
        summary:
          notes[latestSeries.minor]?.tagline ??
          truncate(toPlainText(resolveSummary(latestSeries, notes[latestSeries.minor], dates)), 72),
      }
    : null;

  const cards: SocialCard[] = [
    buildIndexCard(seriesList, dates),
    ...seriesList.map((series) =>
      buildSeriesCard({
        series,
        notes: notes[series.minor],
        dates,
        latest: series.minor === (latestSeries?.minor ?? ""),
      }),
    ),
  ];

  const artifacts: Record<string, string> = {
    [RELEASE_DATES_SOURCE]: `${formatJson(dates)}\n`,
    [LATEST_RELEASE_PATH]: `${formatJson(latest)}\n`,
    [SOCIAL_CARDS_PATH]: `${formatJson(cards)}\n`,
    [resolve(CHANGELOG_OUTPUT_DIR, "index.md")]: renderIndexPage({
      seriesList,
      notes,
      dates,
      card: cards[0] as SocialCard,
    }),
    [CHANGELOG_FEED_PATH]: renderFeed({ seriesList, notes, dates }),
  };

  seriesList.forEach((series, index) => {
    artifacts[resolve(CHANGELOG_OUTPUT_DIR, `${series.minor}.md`)] = renderSeriesPage({
      series,
      card: cards[index + 1] as SocialCard,
      notes: notes[series.minor],
      dates,
      ...(seriesList[index - 1] ? { newer: seriesList[index - 1]?.minor } : {}),
      ...(seriesList[index + 1] ? { older: seriesList[index + 1]?.minor } : {}),
      ...(latestReleasedVersion ? { latestReleasedVersion } : {}),
    });
  });

  return artifacts;
}

/**
 * List generated series pages that no longer correspond to a series in `CHANGELOG.md`.
 *
 * Removing more than half of what is on disk means the parse collapsed rather than a series being
 * renamed, so that case throws instead of quietly deleting committed pages.
 */
function findOrphanedPages(artifacts: Readonly<Record<string, string>>) {
  let existing: string[];
  try {
    existing = readdirSync(CHANGELOG_OUTPUT_DIR);
  } catch {
    return [];
  }

  const pages = existing
    .filter((name) => name.endsWith(".md"))
    .map((name) => resolve(CHANGELOG_OUTPUT_DIR, name));
  const orphaned = pages.filter((path) => !(path in artifacts));

  if (pages.length > 1 && orphaned.length > pages.length / 2) {
    throw new Error(
      `Refusing to remove ${orphaned.length} of ${pages.length} generated changelog pages. ` +
        "This usually means CHANGELOG.md failed to parse rather than that releases were removed.",
    );
  }

  return orphaned;
}

/**
 * List cards whose rendered image is missing.
 *
 * Painting a card needs a browser, so this script records what should exist and reports gaps;
 * `bun run generate:og` is what draws them.
 */
export function findMissingCardImages(cards: readonly SocialCard[]) {
  return cards
    .map((card) => resolve(SOCIAL_CARD_DIR, `${card.slug}.png`))
    .filter((path) => !existsSync(path));
}

/** Write generated artifacts, or report stale paths without modifying them. */
export function updateGeneratedChangelog({
  check = false,
  artifacts = generateChangelogArtifacts(),
}: {
  check?: boolean;
  artifacts?: Readonly<Record<string, string>>;
} = {}) {
  const stalePaths: string[] = [];

  for (const path of findOrphanedPages(artifacts)) {
    stalePaths.push(path);
    if (!check) {
      rmSync(path);
    }
  }

  for (const [path, content] of Object.entries(artifacts)) {
    const current = (() => {
      try {
        return readFileSync(path, "utf8");
      } catch {
        return undefined;
      }
    })();
    if (current === content) {
      continue;
    }
    stalePaths.push(path);
    if (!check) {
      mkdirSync(resolve(path, ".."), { recursive: true });
      writeFileSync(path, content);
    }
  }

  return stalePaths;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const stalePaths = updateGeneratedChangelog({ check });
  if (check && stalePaths.length > 0) {
    console.error("Generated changelog pages are stale:");
    for (const path of stalePaths) {
      console.error(`  ${path}`);
    }
    console.error("Run `bun run generate:changelog` and commit the result.");
    process.exit(1);
  }
  if (!check) {
    console.log(
      stalePaths.length > 0
        ? `Updated ${stalePaths.length} generated changelog file(s).`
        : "Generated changelog is already current.",
    );
  }

  // Card images need a browser, so they are drawn separately. Report the gap either way: a new
  // release otherwise ships with a page whose social card 404s.
  const cards = JSON.parse(readFileSync(SOCIAL_CARDS_PATH, "utf8")) as SocialCard[];
  const missingImages = findMissingCardImages(cards);
  if (missingImages.length > 0) {
    const report = check ? console.error : console.warn;
    report(`Missing ${missingImages.length} social card image(s):`);
    for (const path of missingImages) {
      report(`  ${path}`);
    }
    report("Run `bun run generate:og` and commit the result.");
    if (check) {
      process.exit(1);
    }
  }
}
