import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  CLI_REFERENCE_COMMANDS,
  COMMON_REVIEW_OPTIONS,
  type CliReferenceCommand,
  type CliReferenceOption,
  WATCH_OPTION,
} from "../src/app/cli";
import {
  BUILT_IN_THEME_IDS,
  CONFIG_COMMAND_SECTIONS,
  CONFIG_REFERENCE_CUSTOM_THEME,
  CONFIG_REFERENCE_EXTENSIONS,
  CONFIG_REFERENCE_OPTIONS,
} from "../src/core/run/config";
import { renderHunkReviewSkill } from "../src/hunk-review/skillDocument";
import { type AgentCommandOption, SESSION_AGENT_COMMAND_LIST } from "../src/session/agent/surface";
import {
  DEFAULT_SESSION_BROKER_HOST,
  DEFAULT_SESSION_BROKER_PORT,
  SESSION_BROKER_HOST_ENV,
  SESSION_BROKER_PORT_ENV,
  UNSAFE_ALLOW_REMOTE_SESSION_BROKER_ENV,
} from "../src/session/broker/brokerConfig";

const REPO_ROOT = resolve(import.meta.dir, "..");
const GENERATED_NOTICE =
  "<!-- GENERATED by `bun run generate:docs`. Edit the runtime metadata sources imported by scripts/generate-docs.ts instead. -->";

export const GENERATED_DOC_PATHS = {
  cli: resolve(REPO_ROOT, "website", "src", "content", "docs", "docs", "reference", "cli.md"),
  config: resolve(REPO_ROOT, "website", "src", "content", "docs", "docs", "reference", "config.md"),
  agentSkill: resolve(REPO_ROOT, "website", "public", "docs", "hunk-review-skill.md"),
} as const;

/** Escape prose that Markdown would otherwise parse as inline HTML tags. */
function proseSafe(value: string) {
  return value.replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

/** Escape Markdown table delimiters while preserving inline code. */
function tableCell(value: string) {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br />");
}

/** Render structured CLI options as a Markdown reference table. */
function renderOptionTable(options: readonly (CliReferenceOption | AgentCommandOption)[]) {
  if (options.length === 0) {
    return "This command has no command-specific options.";
  }

  const rows = options.map((option) => {
    const referenceOption = option as CliReferenceOption;
    const details = [
      option.description,
      referenceOption.defaultValue ? `Default: ${referenceOption.defaultValue}.` : undefined,
      referenceOption.hidden ? "Compatibility inverse; omitted from `--help`." : undefined,
      "required" in option && option.required ? "Required." : undefined,
    ]
      .filter(Boolean)
      .join(" ");
    return `| \`${tableCell(option.flag)}\` | ${tableCell(proseSafe(details))} |`;
  });

  return ["| Option | Description |", "| --- | --- |", ...rows].join("\n");
}

/** Format contiguous Markdown table rows so generated output also passes the repository formatter. */
function formatMarkdownTables(markdown: string) {
  const lines = markdown.split("\n");
  for (let start = 0; start < lines.length; start += 1) {
    if (!lines[start]?.startsWith("|")) {
      continue;
    }

    let end = start;
    while (lines[end]?.startsWith("|")) {
      end += 1;
    }
    const rows = lines.slice(start, end).map((line) =>
      line
        .slice(1, -1)
        .split(/(?<!\\)\|/)
        .map((cell) => cell.trim()),
    );
    const widths = rows[0]?.map((_, column) =>
      Math.max(
        3,
        ...rows
          .filter((row) => !row.every((cell) => /^:?-+:?$/.test(cell)))
          .map((row) => row[column]?.length ?? 0),
      ),
    );
    if (!widths || rows.some((row) => row.length !== widths.length)) {
      start = end - 1;
      continue;
    }

    const formatted = rows.map((row) => {
      const separator = row.every((cell) => /^:?-+:?$/.test(cell));
      return `| ${row
        .map((cell, column) =>
          separator ? "-".repeat(widths[column]!) : cell.padEnd(widths[column]!),
        )
        .join(" | ")} |`;
    });
    lines.splice(start, formatted.length, ...formatted);
    start = end - 1;
  }
  return lines.join("\n");
}

/** Render one fenced shell usage block. */
function renderUsage(lines: readonly string[]) {
  return ["```bash", ...lines, "```"].join("\n");
}

/** Render the deterministic exhaustive CLI reference. */
export function renderCliReference() {
  const commandSections = (Object.values(CLI_REFERENCE_COMMANDS) as CliReferenceCommand[]).map(
    (command) => {
      const pieces = [
        `## \`hunk ${command.path}\``,
        "",
        command.summary,
        "",
        "### Usage",
        "",
        renderUsage(command.synopsis),
      ];

      if (command.details && command.details.length > 0) {
        pieces.push(
          "",
          ...command.details.flatMap((detail, index) => (index > 0 ? ["", detail] : [detail])),
        );
      }
      if (command.aliases && command.aliases.length > 0) {
        pieces.push(
          "",
          `**Aliases:** ${command.aliases.map((alias) => `\`${alias}\``).join(", ")}.`,
        );
      }
      if (command.options && command.options.length > 0) {
        pieces.push("", "### Command-specific options", "", renderOptionTable(command.options));
      }
      if (command.watch) {
        pieces.push("", `Also accepts \`${WATCH_OPTION.flag}\`: ${WATCH_OPTION.description}.`);
      }
      if (command.commonReviewOptions) {
        pieces.push("", "Also accepts every [common review option](#common-review-options).");
      }
      if (command.path === "daemon serve") {
        pieces.push(
          "",
          "### Environment",
          "",
          "| Variable | Purpose |",
          "| --- | --- |",
          `| \`${SESSION_BROKER_HOST_ENV}\` | Bind host; defaults to loopback \`${DEFAULT_SESSION_BROKER_HOST}\`. |`,
          `| \`${SESSION_BROKER_PORT_ENV}\` | Bind port; defaults to \`${DEFAULT_SESSION_BROKER_PORT}\`. |`,
          `| \`${UNSAFE_ALLOW_REMOTE_SESSION_BROKER_ENV}\` | Set to \`1\` to allow unsafe non-loopback binding. |`,
        );
      }
      return pieces.join("\n");
    },
  );

  const sessionSections = SESSION_AGENT_COMMAND_LIST.map((command) => {
    const pieces = [
      `### \`hunk ${command.name}\``,
      "",
      command.summary,
      "",
      renderUsage(command.synopsis),
      "",
      renderOptionTable(command.options),
    ];
    if (command.positionals.length > 0) {
      pieces.push(
        "",
        "**Positionals:** " +
          command.positionals
            .map(({ token, description }) =>
              description ? `\`${token}\` — ${proseSafe(description)}` : `\`${token}\``,
            )
            .join("; ") +
          ".",
      );
    }
    if (command.constraints && command.constraints.length > 0) {
      pieces.push(
        "",
        "**Constraints:** " +
          command.constraints
            .map((constraint) => {
              const scope = constraint.documentationScope
                ? `${constraint.documentationScope}, `
                : "";
              return constraint.kind === "exactly-one"
                ? `${scope}exactly one of ${constraint.flags.map((flag) => `\`${flag}\``).join(", ")}`
                : `${scope}at most one of ${constraint.flags.map((flag) => `\`${flag}\``).join(", ")}`;
            })
            .join("; ") +
          ".",
      );
    }
    if (command.examples && command.examples.length > 0) {
      pieces.push("", "**Examples:**", "", renderUsage(command.examples));
    }
    if (command.helpExtra && command.helpExtra.length > 0) {
      pieces.push("", "**Additional input contract:**", "", "```text", ...command.helpExtra, "```");
    }
    return pieces.join("\n");
  });

  return formatMarkdownTables(`---
title: CLI reference
description: Exhaustive generated reference for Hunk commands, options, and live-session controls.
---

${GENERATED_NOTICE}

This reference is generated from the command metadata used by Hunk itself. Run \`hunk --help\` or \`hunk <command> --help\` to inspect the installed version.

## Global options

| Option | Description |
| --- | --- |
| \`-h, --help\` | Show top-level or command-specific help. |
| \`-v, --version\` | Print the installed Hunk version. |

## Common review options

${renderOptionTable(COMMON_REVIEW_OPTIONS)}

\`--experimental\` may also be placed before the review command, as in \`hunk --experimental diff\`.

${commandSections.join("\n\n")}

## \`hunk session\`

Inspect and control live Hunk review sessions through the loopback daemon. Select a session by id or with \`--repo <path>\` where shown.

${sessionSections.join("\n\n")}
`);
}

/** Render the deterministic exhaustive config reference. */
export function renderConfigReference() {
  const optionBlocks = CONFIG_REFERENCE_OPTIONS.map((option) => {
    const aliasDetails = option.aliases?.length
      ? `\n- **Aliases:** ${option.aliases
          .map(({ key, deprecated }) => `\`${key}\`${deprecated ? " (deprecated)" : ""}`)
          .join(", ")}`
      : "";
    const defaultValue =
      option.runtimeDefault !== undefined
        ? `\`${String(option.runtimeDefault)}\``
        : (option.defaultValue ?? "—");
    return `**\`${option.key}\`**\n\n${option.description}\n\n- **Type:** ${option.type}\n- **Accepted:** ${option.accepted}\n- **Built-in default:** ${defaultValue}${aliasDetails}`;
  });
  const sectionRows = Object.entries(CONFIG_COMMAND_SECTIONS).map(
    ([section, description]) => `| \`[${section}]\` | ${description} |`,
  );
  const colorRows = CONFIG_REFERENCE_CUSTOM_THEME.colorKeys.map(
    (key) => `| \`custom_theme.${key}\` | Override the ${key} semantic color. |`,
  );
  const legacyRows = CONFIG_REFERENCE_CUSTOM_THEME.legacySyntaxColorKeys.map(
    (key) => `\`custom_theme.syntax.${key}\``,
  );
  const legacyThemeRows = Object.entries(CONFIG_REFERENCE_CUSTOM_THEME.legacyBaseAliases).map(
    ([alias, replacement]) => `| \`${alias}\` | \`${replacement}\` |`,
  );
  const extensionRows = CONFIG_REFERENCE_EXTENSIONS.keys.map(
    (key) =>
      `| \`${key.key}\` | ${key.type} | ${key.accepted} | ${key.defaultValue ?? "—"} | ${key.description} |`,
  );

  return formatMarkdownTables(`---
title: Config reference
description: Exhaustive generated reference for Hunk TOML keys, defaults, aliases, and layering.
---

${GENERATED_NOTICE}

Hunk reads TOML preferences from the user config and an optional repository config. This reference is generated from the same catalog that \`src/core/run/config.ts\` uses to parse preference keys.

## Resolution and scope

Layers apply from lowest to highest precedence:

1. built-in defaults
2. user config top-level keys, then the matching command table, then \`[pager]\` when pager chrome is active
3. repository \`.hunk/config.toml\` top-level keys, matching command table, and pager table
4. explicit CLI options

The user path is \`$XDG_CONFIG_HOME/hunk/config.toml\` when configured. Otherwise Hunk uses \`$HOME/.config/hunk/config.toml\` or \`%USERPROFILE%/.config/hunk/config.toml\`; if none of those environment variables are set, no user config is loaded. Custom theme tables are root-only; preference keys may appear at top level, in a command table, or in \`[pager]\`.

## Preference keys

${optionBlocks.join("\n\n---\n\n")}

## Command tables

${sectionRows.length > 0 ? ["| Table | Applies to |", "| --- | --- |", ...sectionRows].join("\n") : "No command tables are supported."}

\`[pager]\` is an additional overlay for any review opened with pager-style chrome. It is applied after the matching command table in the same file.

## Custom themes

Set \`theme = "custom"\` and add a root \`[custom_theme]\` table. \`custom_theme.base\` accepts one of these built-in ids and defaults to \`${CONFIG_REFERENCE_CUSTOM_THEME.defaultBase}\` when layered custom themes need a base:

${BUILT_IN_THEME_IDS.map((id) => `- \`${id}\``).join("\n")}

These deprecated IDs remain accepted by \`theme\` and \`custom_theme.base\`, then normalized to their replacements:

| Legacy ID | Replacement |
| --- | --- |
${legacyThemeRows.join("\n")}

\`custom_theme.label\` accepts a non-empty string. Every semantic color below accepts a six-digit \`#rrggbb\` value:

| Key | Description |
| --- | --- |
${colorRows.join("\n")}

### Syntax scopes

\`[${CONFIG_REFERENCE_CUSTOM_THEME.syntaxScopesTable}]\` accepts arbitrary non-empty Shiki/TextMate scope names as TOML keys and six-digit hex colors as values. These exact scope overrides are the preferred syntax customization API.

The deprecated \`[${CONFIG_REFERENCE_CUSTOM_THEME.legacySyntaxTable}]\` table remains accepted for one compatibility window with these semantic keys: ${legacyRows.join(", ")}. Hunk normalizes them into exact scope overrides and emits a startup notice.

### Named themes

Declare any number of additional themes as \`[${CONFIG_REFERENCE_CUSTOM_THEME.namedThemeTable}.<id>]\` tables. Each one accepts exactly the keys \`[${CONFIG_REFERENCE_CUSTOM_THEME.table}]\` accepts, plus the id in the table name, and is selectable with \`theme = "<id>"\` or \`--theme <id>\`. Ids are lowercase words separated by \`-\` or \`_\`; ids belonging to built-in themes, to \`auto\`, or to the \`${CONFIG_REFERENCE_CUSTOM_THEME.table}\` table are skipped with a startup notice. \`[${CONFIG_REFERENCE_CUSTOM_THEME.table}]\` itself keeps the id \`custom\`. Same-id tables merge field by field across the user and repository layers, with the repository layer winning.

## Extensions

\`[${CONFIG_REFERENCE_EXTENSIONS.table}]\` controls which user extensions load. It is root-only and does not accept command or \`[pager]\` overrides.

| Key | Type | Accepted | Built-in default | Description |
| --- | --- | --- | --- | --- |
${extensionRows.join("\n")}

Repository \`.hunk/config.toml\` paths are kept separate from user paths: Hunk prompts for trust before executing repository-declared extension code, and \`--no-extensions\` disables user extensions entirely for one run.

Each extension reads its own settings from a \`[${CONFIG_REFERENCE_EXTENSIONS.perExtensionTable}.<id>]\` table. Hunk does not interpret those keys; it passes the table through to the extension. Repository tables merge over user tables key by key, and Hunk emits a startup notice naming every extension whose settings the repository overrides.
`);
}

/** Produce every committed generated documentation artifact. */
export function generateDocsArtifacts() {
  return {
    [GENERATED_DOC_PATHS.cli]: renderCliReference(),
    [GENERATED_DOC_PATHS.config]: renderConfigReference(),
    [GENERATED_DOC_PATHS.agentSkill]: renderHunkReviewSkill(),
  };
}

/** Write generated artifacts, or report stale paths without modifying them. */
export function updateGeneratedDocs({
  check = false,
  artifacts = generateDocsArtifacts(),
}: {
  check?: boolean;
  artifacts?: Readonly<Record<string, string>>;
} = {}) {
  const stalePaths: string[] = [];
  for (const [path, content] of Object.entries(artifacts)) {
    const current = (() => {
      try {
        return readFileSync(path, "utf8");
      } catch {
        return undefined;
      }
    })();
    if (current === content) {
      continue;
    }
    stalePaths.push(path);
    if (!check) {
      writeFileSync(path, content);
    }
  }
  return stalePaths;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const stalePaths = updateGeneratedDocs({ check });
  if (check && stalePaths.length > 0) {
    console.error("Generated documentation is stale:");
    for (const path of stalePaths) {
      console.error(`  ${path}`);
    }
    console.error("Run `bun run generate:docs` and commit the result.");
    process.exit(1);
  }
  if (!check) {
    console.log(
      stalePaths.length > 0
        ? `Updated ${stalePaths.length} generated documentation file(s).`
        : "Generated documentation is already current.",
    );
  }
}
